version: '3.4'
services:
  user-db:
    image: mysql:8.0
    volumes:
      - user-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_ja_0900_as_cs
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_DB
      TZ: Asia/Tokyo
    ports:
      - "4306:3306"

  user:
    build: 
      context: .
      target: prod
    volumes:
      - .:/app
    depends_on:
      - user-db
    tty: true
    environment:
      TZ: Asia/Tokyo

  blacklist-kvs:
    image: redis:5.0-alpine
    tty: true
    volumes:
      - blacklist-data:/data
    command: ["--requirepass", "password"]

volumes:
  user-data:
  blacklist-data:

networks:
  default:
    external:
      name: fishapp-net