name: Build and Publish to GCR

on:
  push:
    branches:
    - master

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: fishapp-gke-cluster
  IMAGE: auth

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '278.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

    - run: |
        gcloud auth configure-docker

    - name: Build
      run: |
        docker build -t asia.gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA .

    - name: Publish
      run: |
        docker push asia.gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA